### ISSUE TITLE
chi

### ISSUE THREAD

**Issue by lucy3** [snap-stanford/graphwave#4]
Just to clarify, is each row of chi the structural representation for a node? Does the row index correspond to the node's ID in the input networkx graph?

**Comment by CEfanmin** [comment]
I do some experience, it does. Each row of chi representation for a node and row index correspond to the node's ID.

**Comment by donnate** [comment]
Hi,

Thank you for your interest in our method.
This is indeed correct, each row corresponds to a node.
Best regards,

Claire
